postprocessor:
  name: pro2_ent
  APS_mode: True
  postprocessor_args:
    noise_level: 0.0014
  postprocessor_sweep:
    noise_level: [0.00001,0.00005,0.0001,0.0005,0.001,0.005,0.001]
    gd_steps: [1,3,5,7]
