postprocessor:
  name: pro3_msp
  APS_mode: True
  postprocessor_args:
    temperature: 1
    noise_level: 0.001
  postprocessor_sweep:
    noise_level: [0.00005,0.0001,0.0005,0.001,0.005,0.01,0.02]
    gd_steps: [1,3,5,7]
