exp_name: "'@{dataset.name}'_'@{network.name}'_'@{trainer.name}'_e'@{optimizer.num_epochs}'_lr'@{optimizer.lr}'_param'@{trainer.trainer_args.param}'_bs_'@{dataset.train.batch_size}'/s'@{seed}'"

output_dir: ./results/
save_output: True
merge_option: default
seed: 0

num_gpus: 1
num_workers: 8
num_machines: 1
machine_rank: 0

preprocessor:
  name: base

pipeline:
  name: train



trainer:
  name: ish
  trainer_args:
    mode: minksample_expscale
    param: 0.85
    layer: r1


evaluator:
  name: base

optimizer:
  name: sgd
  num_epochs: 100
  lr: 0.1
  momentum: 0.9
  weight_decay: 0.0005
  weight_decay_fc: 0.00005
  nesterov: True
  nesterov_fc: True

recorder:
  name: base
  save_all_models: False
