exp_name: "'@{dataset.name}'_'@{network.name}'_'@{trainer.name}'_e'@{optimizer.num_epochs}'_lr'@{optimizer.lr}'_'@{mark}'/s'@{seed}'"
output_dir: ./results/
save_output: True
merge_option: default
mark: default
seed: 0

num_gpus: 1
num_workers: 8
num_machines: 1
machine_rank: 0

preprocessor:
  name: cider

pipeline:
  name: train

trainer:
  name: reweightood
  trainer_args:
    temp: 0.1
    m_b: 5.0
    c_b: 4.0
    m_w: 2.0
    c_w: 1.0

evaluator:
  name: base

optimizer:
  name: sgd
  num_epochs: 100
  lr: 0.1
  momentum: 0.9
  weight_decay: 0.0001
  warm: True
  cosine: True
  lr_decay_rate: 0.1
  lr_decay_epochs: [50, 75, 90]

recorder:
  name: cider
  save_all_models: False
